---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb
  labels:
    app: ueransim
    component: gnb
spec:
  selector:
    matchLabels:
      app: ueransim
      component: gnb
  replicas: 
  template:
    metadata:
      labels:
        app: ueransim
        component: gnb
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n2network", "interface": "n2", "ips": [ "10.10.2.22/24" ] },
          { "name": "n3network", "interface": "n3", "ips": [ "10.10.3.22/24" ] },
          { "name": "n6network", "interface": "nran", "ips": [ "10.10.6.22/24" ] }
          ]'
    spec:
      containers:
      - image: free5gc/ueransim:v3.4.1
        name: gnb
        ports:
        - name: gnb-ue
          containerPort: 4997
          protocol: UDP
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: ["./nr-gnb", "-c", "./config/gnbcfg.yaml"]
        volumeMounts:
        - name: gnb-volume
          mountPath: /ueransim/config/
        - name: tun-device
          mountPath: /dev/net/
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: gnb-volume
        projected:
          sources:
          - configMap:
              name: gnb-configmap
      - name: tun-device
        hostPath:
          path: /dev/net/tun
