apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nwdaf
  labels:
    app: free5gc
    nf: nwdaf
spec:
  selector:
    matchLabels:
      app: free5gc
      nf: nwdaf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc
        nf: nwdaf
    spec:
      containers:
      - image: edierbra/free5gc:v3.2.0
        name: nwdaf
        ports:
        - containerPort: 29531
        command: ["./nwdaf"]
        args: ["--config", "config/nwdafcfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: nwdaf-volume
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: nwdaf-volume
        projected:
          sources:
          - configMap:
              name: nwdaf-configmap