---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue1
  labels:
    app: ueransim
    component: ue
    name: ue1
spec:
  selector:
    matchLabels:
      app: ueransim
      component: ue
      name: ue1
  replicas: 
  template:
    metadata:
      labels:
        app: ueransim
        component: ue
        name: ue1
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n6network", "interface": "nran", "ips": [ "10.10.6.23/24" ] },
          { "name": "n2network", "interface": "n2", "ips": [ "10.10.2.23/24" ] }
          ]'
    spec:
      containers:
      - image: free5gc/ueransim:v3.4.1
        name: ue
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: ["./nr-ue", "-c", "./config/ue1cfg.yaml"]
        volumeMounts:
        - name: ue1-volume
          mountPath: /ueransim/config/
        - name: tun-device
          mountPath: /dev/net/
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: ue1-volume
        projected:
          sources:
          - configMap:
              name: ue1-configmap
      - name: tun-device
        hostPath:
          path: /dev/net/tun
