apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-configmap
  labels:
    app: free5gc
    nf: smf
    name: smf
data:
  smfcfg.yaml: |
    info:
      version: 1.0.7
      description: SMF initial local configuration

    configuration:
      smfName: SMF # the name of this SMF
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: smf-nsmf # smf.free5gc.org # IP used to register to NRF
        bindingIPv4: 0.0.0.0 # smf.free5gc.org # IP used to bind the service
        port: 8000 # Port used to bind the service
        tls: # the local path of TLS key
          key: cert/smf.key # SMF TLS Certificate
          pem: cert/smf.pem # SMF TLS Private key
      serviceNameList: # the SBI services provided by this SMF, refer to TS 29.502
        - nsmf-pdusession # Nsmf_PDUSession service
        - nsmf-event-exposure # Nsmf_EventExposure service
        - nsmf-oam # OAM service
      snssaiInfos: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
        - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
            sst: 1 # Slice/Service Type (uinteger, range: 0~255)
            sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
          dnnInfos: # DNN information list
            - dnn: internet # Data Network Name
              dns: # the IP address of DNS
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
        - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
            sst: 1 # Slice/Service Type (uinteger, range: 0~255)
            sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
          dnnInfos: # DNN information list
            - dnn: internet # Data Network Name
              dns: # the IP address of DNS
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
      plmnList: # the list of PLMN IDs that this SMF belongs to (optional, remove this key when unnecessary)
        - mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      locality: area1 # Name of the location where a set of AMF, SMF, PCF and UPFs are located
      pfcp: # the IP address of N4 interface on this SMF (PFCP)
        # addr config is deprecated in smf config v1.0.3, please use the following config
        nodeID: 10.10.4.101 # smf.free5gc.org # the Node ID of this SMF
        listenAddr: 10.10.4.101 # smf.free5gc.org # the IP/FQDN of N4 interface on this SMF (PFCP)
        externalAddr: 10.10.4.101 # smf.free5gc.org # the IP/FQDN of N4 interface on this SMF (PFCP)
      userplaneInformation: # list of userplane information
        upNodes: # information of userplane node (AN or UPF)
          gNB1: # the name of the node
            type: AN # the type of the node (AN or UPF)
          UPF: # the name of the node
            type: UPF # the type of the node (AN or UPF)
            nodeID: 10.10.4.1 # upf.free5gc.org # the Node ID of this UPF
            addr: 10.10.4.1 # upf.free5gc.org # the IP/FQDN of N4 interface on this UPF (PFCP)
            sNssaiUpfInfos: # S-NSSAI information list for this UPF
              - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
                  sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                  sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                dnnUpfInfoList: # DNN information list for this S-NSSAI
                  - dnn: internet
                    pools:
                      - cidr: 10.60.0.0/16
                    staticPools:
                      - cidr: 10.60.100.0/24
              - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
                  sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                  sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                dnnUpfInfoList: # DNN information list for this S-NSSAI
                  - dnn: internet
                    pools:
                      - cidr: 10.61.0.0/16
                    staticPools:
                      - cidr: 10.61.100.0/24
            interfaces: # Interface list for this UPF
              - interfaceType: N3 # the type of the interface (N3 or N9)
                endpoints: # the IP address of this N3/N9 interface on this UPF
                  - 10.10.3.1 # upf.free5gc.org
                networkInstances: # Data Network Name (DNN)
                  - internet
        links: # the topology graph of userplane, A and B represent the two nodes of each link
          - A: gNB1
            B: UPF
      # retransmission timer for pdu session modification command
      t3591:
        enable: true # true or false
        expireTime: 16s # default is 6 seconds
        maxRetryTimes: 3 # the max number of retransmission
      # retransmission timer for pdu session release command
      t3592:
        enable: true # true or false
        expireTime: 16s # default is 6 seconds
        maxRetryTimes: 3 # the max number of retransmission
      nrfUri: http://nrf-nnrf:8000 # a valid URI of NRF
      nrfCertPem: cert/nrf.pem # NRF Certificate
      urrPeriod: 10 # default usage report period in seconds
      urrThreshold: 1000 # default usage report threshold in bytes
      requestedUnit: 1000
    logger: # log output setting
      enable: true # true or false
      level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      reportCaller: false # enable the caller report or not, value: true or fals

  uerouting.yaml: |
    info:
      version: 1.0.7
      description: Routing information for UE

    ueRoutingInfo: # the list of UE routing information
      UE1: # Group Name
        members:
        - imsi-208930000007487 # Subscription Permanent Identifier of the UE
        topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
        # default path derived from this topology
        # node name should be consistent with smfcfg.yaml
          - A: gNB1
            B: BranchingUPF
          - A: BranchingUPF
            B: AnchorUPF1
        specificPath:
          - dest: 10.60.0.103/32 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            path: [BranchingUPF, AnchorUPF2]

      UE2: # Group Name
        members:
        - imsi-208930000007486 # Subscription Permanent Identifier of the UE
        topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
        # default path derived from this topology
        # node name should be consistent with smfcfg.yaml
          - A: gNB1
            B: BranchingUPF
          - A: BranchingUPF
            B: AnchorUPF1
        specificPath:
          - dest: 10.0.0.11/32 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            path: [BranchingUPF, AnchorUPF2]

    routeProfile: # Maintains the mapping between RouteProfileID and ForwardingPolicyID of UPF
      MEC1: # Route Profile identifier
        forwardingPolicyID: 10 # Forwarding Policy ID of the route profile

    pfdDataForApp: # PFDs for an Application
      - applicationId: edge # Application identifier
        pfds: # PFDs for the Application
          - pfdID: pfd1 # PFD identifier
            flowDescriptions: # Represents a 3-tuple with protocol, server ip and server port for UL/DL application traffic
              - permit out ip from 10.60.0.1 8080 to any
