apiVersion: v1
kind: Service
metadata:
  name: webui-service
  labels:
    app: free5gc
spec:
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30550
  selector:
    app: free5gc
