apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nrf
  labels:
    app: free5gc
    nf: nrf
spec:
  selector:
    matchLabels:
      app: free5gc
      nf: nrf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc
        nf: nrf
    spec:
      initContainers:
      - name: wait-mongo
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: db:27017
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the MongoDB; sleep 2; done;"]
      containers:
      - image: free5gc/nrf:v3.4.1
        name: nrf
        ports:
        - containerPort: 8000
        command: ["./nrf", "-c", "./config/nrfcfg.yaml"]
        env: 
          - name: DB_URI
            value: mongodb://db/free5gc
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: nrf-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: nrf-volume
        projected:
          sources:
          - configMap:
              name: nrf-configmap
