apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nssf
  labels:
    app: free5gc
    nf: nssf
spec:
  selector:
    matchLabels:
      app: free5gc
      nf: nssf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc
        nf: nssf
    spec:
      initContainers:
        - name: wait-udr
          image: busybox:1.32.0
          env:
          - name: DEPENDENCIES
            value: udr-nudr:8000
          command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the UDR; sleep 2; done;"]
      containers:
      - image: free5gc/nssf:v3.4.1
        name: nssf
        ports:
        - containerPort: 8000
        command: ["./nssf", "-c", "./config/nssfcfg.yaml"]   
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: nssf-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: nssf-volume
        projected:
          sources:
          - configMap:
              name: nssf-configmap
